### ISSUE TITLE
Improve 'install procedure'

### ISSUE THREAD

**Issue by dalanicolai** [jasonm23/markdown-soma#7]
I just tried this package, and although it looks like it pulled in a huge amount of rust dependencies, it finally works great!

However, the installation from Melpa did not work because the `main` and `styles` directories are not pulled and neither the cargo scripts.

I guess for it to work you should 'extend' the recipe on Melpa with the `:files` keyword
so that it looks like something as follows:
```
(markdown-soma :fetcher github
               :repo "jasonm23/markdown-soma"
               :files (:defaults "*.lock" "*.toml"
                                 "src" "styles"))
```
(I am not sure if you need both the lock and toml files, I have no idea about cargo)

Then finally, and optionally, you could create some elisp function that runs the required installation commands (similar to how `pdf-tools` provides the `pdf-tools-install` command).

Thanks a lot for the great package. I works wonderfully (especially with the built-in xwidget webkit browser)!

**Comment by jasonm23** [comment]
Thanks, I saw another package do this too, and had planned to add on better install mechanic.

TODO list +1

**Comment by lebensterben** [comment]
I think it doesn't need to ship with those additional files except styles/.

In markdown-soma.el we can install the binary with `cargo install --git=https://github.com/jasonm23/markdown-soma`.

**Comment by jasonm23** [comment]
Big assumption that cargo will be available

**Comment by lebensterben** [comment]
@jasonm23 but the current installation instruction already needs cargo.

**Comment by jasonm23** [comment]
Sorry? Do you see no difference?

Outlining what's needed vs automatically assuming dependencies exist?

**Comment by jasonm23** [comment]
Anyway to avoid further helpful insights.  The install procedure will mirror that of other packages which use rust binaries.  Specifically it will be based on Emacs parinfer-rust.

Any other additional contributions will take the form of a PR.
